services:
  tansu:
    image: ghcr.io/tansu-io/tansu:0.6.0
    ports:
      - "9092:9092"
    environment:
      - ADVERTISED_LISTENER_URL=tcp://localhost:9092
    post_start:
      - command: ["/tansu", "topic", "create", "default"]
